<?php
$priceHelper = $block->getPricingObject();
$collectorConfig = $block->getCollectorConfig();
$customerType = $collectorConfig->getCustomerType();
$url = $block->getBaseUrl();
$updateCustomer = $collectorConfig->getUpdateCustomer();
$showDiscount = $collectorConfig->getShowDiscount();
$checkoutHelper = $block->getCheckoutHelper();
?>
<script>
    var cajaxurl = "<?php echo $url . "collectorcheckout/cajax/cajax"; ?>";
    <?php if ($updateCustomer): ?>
    var shouldUpdateCustomer = true;
    <?php else: ?>
    var shouldUpdateCustomer = false;
    <?php endif; ?>
</script>
<div class="collector-cart" id="collector-cart">
    <?php if ($customerType == \Collector\Iframe\Model\Config\Source\Customertype::PRIVATE_BUSINESS_CUSTOMER): ?>
        <div id="col-businesstypes" style="float:right;">
            <a class="col-btype col-active" id="b2c"><?php echo __('Private'); ?></a> | <a
                    class="col-btype col-inactive" id="b2b"><?php echo __('Company'); ?></a>
        </div>
    <?php endif; ?>
    <h2 class="col-checkout col-title"><?php echo __('Cart') ?></h2>
    <div id="area-spinner-container" class="area-spinner-container">
        <div class="spinner-animation">&nbsp;</div>
    </div>
    <div id="col-table-responsive" class="col-table-responsive">
        <div class="collector-checkout-cart-table">
            <div class="collector-checkout-table-head">
                <div class="collector-checkout-product-head">
                    <?php echo __('Product') ?>
                </div>
                <div class="collector-checkout-price-head">
                    <?php echo __('Price') ?>
                </div>
                <div class="collector-checkout-qty-head">
                    <?php echo __('qty') ?>
                </div>
            </div>
            <span id="collector-checkout-line" class="collector-checkout-line"></span>
            <?php foreach ($this->getProducts() as $product): ?>
                <div class="collector-checkout-product-row">
                    <div class="collector-checkout-img">
                        <img src="<?php echo $product['img'] ?>" alt="logo">
                    </div>
                    <div class="collector-checkout-name">
                        <p><?php echo $product['name'] ?></p>
                        <?php if (count($product['options'])) {
                            ?>
                            <dl>
                            <?php foreach ($product['options'] as $option): ?>
                                <dd><?php echo $option ?></dd>
                            <?php endforeach; ?>
                            </dl><?php
                        } ?>
                    </div>
                    <div class="collector-checkout-qty" id="qty_ <?php echo $product['id'] ?>">
                        <button class="collector-checkout-button-sub col-sub"
                                id="col-sub-btn sub_<?php echo $product['id'] ?>" name="sub">-
                        </button>
                        <div class="collector-checkout-product-qty"><?php echo $product['qty'] ?></div>
                        <button id="col-inc-btn inc_<?php echo $product['id'] ?>"
                                class="collector-checkout-button-inc col-inc" name="inc">+
                        </button>
                    </div>
                    <div class="collector-checkout-sum" id="sum_<?php echo $product['id'] ?>">
                        <?php echo $product['sum'] ?>
                    </div>
                    <div class="collector-checkout-del-but col-del" id="del_<?php echo $product['id'] ?>">
                        <span id="col-del-btn del_<?php echo $product['id'] ?>"
                              class="collector-checkout-button-del col-del" style="height: auto; width: auto;"
                              name="del"></span>
                    </div>
                    <span id="collector-checkout-line" class="collector-checkout-line"></span>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div id="col-totals-table" class="col-totals-table">
        <table class="col-totals">
            <?php if ($this->hasDiscount()): ?>
                <?php $code = "";
                $discountCode = $block->getQuoteCouponCode();
                if (!empty($discountCode)) {
                    $code = "(" . $discountCode . ")";
                } ?>
                <tr>
                    <td class="col-name"><?php echo __('Discount');
                        echo " " . $code; ?></td>
                    <td class="col-price"><?php echo $this->getDiscount(); ?></td>
                </tr>
            <?php endif; ?>
            <?php $totals = $this->getTotals();
            foreach ($totals as $total): ?>
                <?php
//                var_dump($total->getData());
                if (array_key_exists('value_incl_tax', $total->getData())) {
                    if (isset($total->getData()['value_incl_tax'])) {
                        if ($total->getData()['value_incl_tax'] > 0) {
                        } else {
                            continue;
                        }
                    } else {
                        if (array_key_exists('value', $total->getData())) {
                            if ($total->getData()['value'] > 0) {
                            } else {
                                continue;
                            }
                        }
                    }
                } else {
                    if (array_key_exists('value', $total->getData())) {
                        if ($total->getData()['value'] > 0) {
                        } else {
                            continue;
                        }
                    } else {
                        continue;
                    }
                }
                ?>
                <tr>
                    <td class="col-name">
                        <?php if ($total->getData()['code'] == 'grand_total') { ?>
                            <span class="col-grandname"><?php echo $total->getData()['title']; ?></span>
                            <?php
                        } else {
                            if (array_key_exists('value_incl_tax', $total->getData())) {
                                if (isset($total->getData()['value_incl_tax'])) {
                                    if ($total->getData()['value_incl_tax'] > 0) {
                                        echo $total->getData()['title'];
                                    }
                                } else {
                                    if (array_key_exists('value', $total->getData())) {
                                        if ($total->getData()['value'] > 0) {
                                            echo $total->getData()['title'];
                                        }
                                    }
                                }
                            } else {
                                if (array_key_exists('value', $total->getData())) {
                                    if ($total->getData()['value'] > 0) {
                                        echo $total->getData()['title'];
                                    }
                                }
                            }
                        } ?>
                    </td>
                    <?php if ($total->getData()['code'] == 'grand_total'){ ?>
                    <td class="col-price col-grand">
                        <?php }else{ ?>
                    <td class="col-price">
                        <?php } ?>
                        <?php
                        if ($total->getData()['code'] == 'shipping') {
                            echo $this->getShippingPrice();
                        } else if ($total->getData()['code'] == 'grand_total') {
                            if (empty($totals['shipping']->getData()['title']->getArguments())) {
                                echo $checkoutHelper->formatPrice($total->getData()['value'] + $priceHelper->currency($this->getShippingPriceExclFormatting(), false, false) + $priceHelper->currency($collectorConfig->getInvoiceB2BFee(), false, false));
                            } else {
                                if (array_key_exists('value_incl_tax', $total->getData())) {
                                    if (isset($total->getData()['value_incl_tax'])) {
                                        echo $checkoutHelper->formatPrice($total->getData()['value_incl_tax'] + $priceHelper->currency($collectorConfig->getInvoiceB2BFee(), false, false));
                                    } else {
                                        echo $checkoutHelper->formatPrice($total->getData()['value'] + $priceHelper->currency($collectorConfig->getInvoiceB2BFee(), false, false));
                                    }
                                } else {
                                    echo $checkoutHelper->formatPrice($total->getData()['value'] + $priceHelper->currency($collectorConfig->getInvoiceB2BFee(), false, false));
                                }
                            }
                        } else if ($total->getData()['code'] == 'fee_amount') {
                            if (array_key_exists('value_incl_tax', $total->getData())) {
                                if (isset($total->getData()['value_incl_tax'])) {
                                    echo $checkoutHelper->formatPrice($total->getData()['value_incl_tax'] + $priceHelper->currency($collectorConfig->getInvoiceB2BFee(), false, false));
                                } else {
                                    if ($total->getData()['value'] > 0) {
                                        echo $checkoutHelper->formatPrice($total->getData()['value'] + $priceHelper->currency($collectorConfig->getInvoiceB2BFee(), false, false));
                                    }
                                }
                            } else {
                                if ($total->getData()['value'] > 0) {
                                    echo $checkoutHelper->formatPrice($total->getData()['value'] + $priceHelper->currency($collectorConfig->getInvoiceB2BFee(), false, false));
                                }
                            }
                        } else {
                            if (array_key_exists('value_incl_tax', $total->getData())) {
                                if (isset($total->getData()['value_incl_tax'])) {
                                    echo $checkoutHelper->formatPrice($total->getData()['value_incl_tax']);
                                } else {
                                    if (array_key_exists('value', $total->getData())) {
                                        echo $checkoutHelper->formatPrice($total->getData()['value']);
                                    }
                                }
                            } else {
                                if (array_key_exists('value', $total->getData())) {
                                    echo $checkoutHelper->formatPrice($total->getData()['value']);
                                }
                            }
                        }
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <?php if ($showDiscount): ?>
            <div class="collector-checkout-discount">
                <form action="javascript:void(0);">
                    <?php if ($this->hasCoupon()) { ?>
                        <input type="text" name="code" id="col-code" class="col-code"
                               value="<?php echo $block->getQuoteCouponCode();; ?>">
                        <input type="button" id="col-codeButton" class="col-codeButton"
                               value="<?php echo __('Cancel') ?>">
                    <?php } else { ?>
                        <input type="text" name="code" placeholder="<?php echo __('Discount Code') ?>" id="col-code"
                               class="col-code">
                        <input type="button" id="col-codeButton" class="col-codeButton" value="<?php echo __('Use') ?>">
                    <?php } ?>
                </form>
            </div>
            <script>
                document.getElementById("col-code").addEventListener("keyup", function (event) {
                    event.preventDefault();
                    if (event.keyCode == 13) {
                        document.getElementById("col-codeButton").click();
                    }
                });
            </script>
        <?php endif; ?>
        <div class="letter_methods newsletter">
            <form>
                <input type="checkbox" class="newsletter-checkbox" id="newsletter-checkbox">
                <label for="newsletter-checkbox"
                       class="checkbox_label"><?php echo __('I want to sign up for the newsletter'); ?></label>
            </form>
        </div>

    </div>

</div>
