<?php if ($block->isVisible()) { ?>
    <?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
    <?php $_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
    <?php $_fax = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Fax') ?>
    <div class="collector_shipping_address">
        <h1>Shipping Address</h1>
        <form class="form-address-edit form-shipping-address"
              action=""
              method="post"
              id="form-validate"
              enctype="multipart/form-data"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend>
                <br>
                <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
                <div class="field street required">
                    <label for="street_1" class="label">
                        <span><?= $block->escapeHtml(__('Street Address')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="street_1"
                               data-mage-init='{"validation":{}}' data-validate="{required:true}"
                               value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                               id="street_1"
                               class="validate input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"/>
                        <input type="text"
                               name="street_2"
                               value="<?= $block->escapeHtmlAttr($block->getStreetLine(2)) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                               id="street_2"
                               data-mage-init='{"validation":{}}'
                               class="input-text"/>
                    </div>
                </div>

                <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
                    <div class="field taxvat">
                        <label class="label" for="vat_id">
                            <span><?= $block->escapeHtml(__('VAT Number')) ?></span>
                        </label>
                        <div class="control">
                            <input type="text"
                                   name="vat_id"
                                   value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                                   title="<?= $block->escapeHtmlAttr(__('VAT Number')) ?>"
                                   data-mage-init='{"validation":{}}'
                                   class="validate input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id')) ?>"
                                   id="vat_id">
                        </div>
                    </div>
                <?php endif; ?>
                <div class="field city required">
                    <label class="label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
                    <div class="control">
                        <input type="text"
                               name="city"
                               data-mage-init='{"validation":{}}'
                               data-validate="{required:true}"
                               value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                               title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                               class="validate input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>"
                               id="city">
                    </div>
                </div>
                <div class="field region required">
                    <label class="label" for="region_id">
                        <span><?= $block->escapeHtml(__('State/Province')) ?></span>
                    </label>
                    <div class="control">
                        <select id="region_id" name="region_id"
                                title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                                data-mage-init='{"validation":{}}'
                                class="validate validate-select" <?= /* @noEscape */
                        !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                            <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                        </select>
                        <input type="text"
                               id="region"
                               name="region"
                               data-mage-init='{"validation":{}}'
                               value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                               title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                               class="validate input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>
                    </div>
                </div>
                <div class="field zip required">
                    <label class="label" for="zip">
                        <span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="postcode"
                               data-mage-init='{"validation":{}}'
                               data-validate="{required:true,'validate-zip-international':true}"
                               value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>"
                               id="zip"
                               class="validate input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
                    </div>
                </div>
                <div class="field country required">
                    <label class="label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
                    <div class="control">
                        <?= $block->getCountryHtmlSelect() ?>
                    </div>
                </div>
            </fieldset>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend>
                <br>
                <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden" data-mage-init='{"validation":{}}' name="success_url"
                       value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
                <input type="hidden" data-mage-init='{"validation":{}}' name="error_url"
                       value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
                <?= $block->getNameBlockHtml() ?>


                <div class="field firstname required">
                    <label class="label" for="shipping_firstname">
                        <span><?= $block->escapeHtml(__('First name')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="firstname"
                               data-mage-init='{"validation":{}}'
                               data-validate="{required:true}"
                               value="<?= $block->escapeHtmlAttr($block->getAddress()->getFirstname()) ?>"
                               title="<?= $block->escapeHtmlAttr(__('First name')) ?>"
                               id="shipping_firstname"
                               class="validate input-text ">
                    </div>
                </div>

                <div class="field lastname required">
                    <label class="label" for="shipping_lastname">
                        <span><?= $block->escapeHtml(__('Last name')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="lastname"
                               data-mage-init='{"validation":{}}'
                               data-validate="{required:true}"
                               value="<?= $block->escapeHtmlAttr($block->getAddress()->getLastname()) ?>"
                               title="<?= $block->escapeHtmlAttr(__('Last name')) ?>"
                               id="shipping_lastname"
                               class="validate input-text ">
                    </div>
                </div>

                <?php if ($_company->isEnabled()): ?>
                    <?= $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
                <?php endif ?>

                <?php if ($_telephone->isEnabled()): ?>
                    <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
                <?php endif ?>

                <?php if ($_fax->isEnabled()): ?>
                    <?= $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
                <?php endif ?>

            </fieldset>
        </form>
    </div>
    <script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */
        $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */
        $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int)$block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */
        $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
    </script>
    <script type="text/javascript">window.showCollectorShipping = true;</script>
<?php } else {
    ?>
    <script type="text/javascript"> window.showCollectorShipping = false; </script>
    <?php
} ?>

