<?php
if (empty($block->getCollectorSession()->getVariable('collector_public_token'))) {
    $storeManager = $block->getStoreManagerObject();
    $url = $storeManager->getStore()->getBaseUrl();
    if (headers_sent()) {
        echo '<script>location.href="' . $url . '";</script>';
    } else {
        die('<script>location.href="' . $url . '";</script>');
    }
} else {
    $url = $block->getCollectorSession()->getVariable('collector_url');
    $dataLang = $block->getCollectorSession()->getVariable('collector_language');
    $dataVariant = $block->getCollectorSession()->getVariable('collector_data_variant');
    $publicToken = $block->getCollectorSession()->getVariable('collector_public_token');
    $block->getCollectorSession()->setVariable('collector_public_token','');
    ?>

    <script>
        require([
            'Magento_Customer/js/customer-data'
        ], function (customerData) {
            var sections = ['cart'];
            customerData.invalidate(sections);
        });
    </script>
    <div id="collector-checkout" class="collector-checkout">
        <script src="<?php echo $url; ?>" data-token="<?php echo $publicToken; ?>"
                data-lang='<?php echo $dataLang; ?>' <?php echo $dataVariant; ?>></script>
    </div>
<?php } ?>